#!/bin/bash

FILE=$1

REQ_MONTH=$2

ACT_YEAR=$(date +%Y) 

ACTIVE_OUTPUT=false

START_YEAR= 
START_MONTH= 
START_DAY= 
START_HH= 
START_MM= 

while read -r line
do

#echo $line
	
if [ "$line" = "BEGIN:VEVENT" ]
then
	ACTIVE_OUTPUT=true
fi 


if $ACTIVE_OUTPUT 
then
 #split by colon
 key=$(echo "$line" | awk -F ':' '{print $1}')
 value=$(echo "$line" | awk -F ':' '{print $2}')



case "$key" in
		DTSTART*) 
				START_YEAR=${value:0:4}
				START_MONTH=${value:4:2}
				START_DAY=${value:6:2}
				START_HH=${value:9:2}
				START_MM=${value:11:2}
				if [ "$REQ_MONTH" != "$START_MONTH" ]
				then
					ACTIVE_OUTPUT=false
				else
					echo -n "$START_DAY.$START_MONTH.$START_YEAR "
				fi 
		;;
		DTEND*)
				YEAR=${value:0:4}
				MONTH=${value:4:2}
				DAY=${value:6:2}
				HH=${value:9:2}
				MM=${value:11:2}
				HOUR_LENGTH=$(echo " $HH - $START_HH" | bc)
				MIN_LENGTH=$(echo " $MM - $START_MM" | bc)

				if [[ MIN_LENGTH -lt 0 ]]
				then
					MIN_LENGTH=$(( $MIN_LENGTH + 60 ))
					HOUR_LENGTH=$(( $HOUR_LENGTH - 1))
				fi 
				echo "$HOUR_LENGTH $MIN_LENGTH"

#				echo "End: $DAY.$MONTH.$YEAR um $HH:$MM Uhr"
		;;
		*) ;;
esac

fi 

if [ "$line" = "END:VEVENT" ]
then 
	ACTIVE_OUTPUT=false 
fi


done < <(dos2unix < $FILE )
